version: "3.9"
services:
  redis:
    container_name: Redis
    image: redis:alpine
    ports:
      - "6379:6379"
    expose:
      - 6379
    restart: always
    volumes:
      - redis_data:/data/
      - /etc/localtime:/etc/localtime:ro
  
  mongodb:
    container_name: MongoDB
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db
      - ./init.js:/docker-entrypoint-initdb.d/init.js:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=redbox-accounts

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    links:
      - redis
    depends_on: 
      - redis
  
  background_services:
    container_name: background_services
    image: background-services:latest
    volumes:
      - ./appsettings.json:/app/appsettings.json
    links:
      - redis
    depends_on: 
      - redis

volumes:
  redis_data:
    external: true
  mongo_data:
    external: true