version: "3.9"
services:
  redis:
    container_name: Redis
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data/
      - /etc/localtime:/etc/localtime:ro
  
  mongodb:
    container_name: MongoDB
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db
      - ./init.js:/docker-entrypoint-initdb.d/init.js
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=redbox

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    command: --cleanup --interval 3600

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
volumes:
  redis_data:
    external: true
  mongo_data:
    external: true